---
title: "Project_1"
author: "Yineng Chen"
date: "2020/6/11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
```

## Loading and preprocessing the data

```{r}
dir.create("data")
unzip("activity.zip",exdir = "data")
activity = read_csv("./data/activity.csv",col_types = "ici", na = "NA")

activity = activity %>% mutate(date = as.Date(date,  "%Y-%m-%d"))

```

## What is mean total number of steps taken per day?

1. Calculate the total number of steps taken per day

```{r}
step_perday = aggregate(activity$steps, list(activity$date), sum,na.rm = T)

names(step_perday)[1] = "date"
names(step_perday)[2] = "steps"

```

2.  Make a histogram of the total number of steps taken each day

```{r}

ggplot(data = step_perday, aes(x = steps)) + 
  geom_histogram(fill = "pink", binwidth = 1000) +
  labs(title = "Daily Steps", x = "Steps", y = "Frequency")

```

3. Calculate and report the mean and median of the total number of steps taken per day

```{r}
mean_step = mean(step_perday$steps,na.rm = TRUE)
median_step = median(step_perday$steps,na.rm = TRUE)

output = cbind(mean_step,median_step)
output
```

